apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    project: golang-demo
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 3000  # Port on Load Balancer
      targetPort: 8080  # Port on POD
  type: LoadBalancer