apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name      : goapp-listener
      protocol  : TCP
      port      : {{ .Values.service.port }}        # Port on Load Balancer
      targetPort: {{ .Values.service.targetPort }}  # Port on POD
  type: {{ .Values.service.type }} 
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
